// Copyright 2016 Google Inc. Use of this source code is governed by an
// MIT-style license that can be found in the LICENSE file or at
// https://opensource.org/licenses/MIT.
//
// Ported and rearchitected for Go by Luka Zakrajsek.

package extend

// dart-source: lib/src/extend/extension_store.dart (DefaultExtensionStore subclass;
// concrete tracking store: addSelector/addExtension/extendList algorithm,
// extendCompound/unify/trim, cross-module AddExtensions, Clone)

import (
	"errors"
	"fmt"

	"github.com/bancek/go-sass/box"
	"github.com/bancek/go-sass/linkedhashmap"
	"github.com/bancek/go-sass/sasscommon"
	"github.com/bancek/go-sass/value"
)

// DefaultExtensionStore is the tracking ExtensionStore. It indexes every
// simple selector to the selector lists containing it, every extended
// target to its source extensions, and every extender component back to the
// extensions it defines, then rewrites registered selectors as new @extend
// rules arrive and as downstream module stores merge in.
//
// The worked core is extendList → extendComplex → extendCompound →
// extendSimple: each compound component expands to a set of extender
// choices, the cross product of those choices is unified, and the results
// are woven back into complex selectors and trimmed. Originals and source
// specificity guard trimming under the first and second laws of extend;
// media contexts restrict which extensions may apply where.
type DefaultExtensionStore struct {
	nextBoxID uint64

	// selectors maps every simple selector in the stylesheet to the selector
	// boxes containing it, so an @extend can find which selectors to adjust.
	selectors *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashSet[*box.ModifiableBox[*value.SelectorList]]]

	// extensions maps every extended target to its source extensions keyed
	// by extender complex selector.
	extensions *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]]

	// extensionsByExtender maps every simple selector appearing in an
	// extender to the extensions that extender defines, so a newly added
	// extension can itself be extended.
	extensionsByExtender *linkedhashmap.LinkedHashMap[value.SimpleSelector, []Extension]

	// mediaContexts records the media query context each CSS selector was
	// defined in. Top-level selectors have no entry.
	mediaContexts *linkedhashmap.LinkedHashMap[*box.ModifiableBox[*value.SelectorList], []*value.CssMediaQuery]

	// sourceSpecificity maps each simple selector to the maximum specificity
	// of the complex selector that originally contained it. Only original
	// selectors count: selectors generated by @extend add no new
	// specificity. Trimming consults this under the second law of extend.
	sourceSpecificity *linkedhashmap.LinkedHashMap[value.SimpleSelector, int]

	// originals holds the complex selectors that were originally part of
	// their selector lists, as opposed to added by @extend. Trimming never
	// drops them, under the first law of extend.
	originals map[*value.ComplexSelector]struct{}

	// mode controls normal @extend versus selector-replace/selector-extend
	// function behavior.
	mode ExtendMode
}

// NewDefaultExtensionStore creates a store in normal @extend mode.
func NewDefaultExtensionStore() *DefaultExtensionStore {
	return NewDefaultExtensionStoreWithMode(ExtendModeNormal)
}

// NewDefaultExtensionStoreWithMode creates a store in the given mode, for
// @extend versus the selector-replace/selector-extend functions.
func NewDefaultExtensionStoreWithMode(mode ExtendMode) *DefaultExtensionStore {
	return &DefaultExtensionStore{
		selectors:            linkedhashmap.New[value.SimpleSelector, *linkedhashmap.LinkedHashSet[*box.ModifiableBox[*value.SelectorList]]](value.SimpleSelectorEquals),
		extensions:           linkedhashmap.New[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]](value.SimpleSelectorEquals),
		extensionsByExtender: linkedhashmap.New[value.SimpleSelector, []Extension](value.SimpleSelectorEquals),
		mediaContexts:        linkedhashmap.New[*box.ModifiableBox[*value.SelectorList], []*value.CssMediaQuery](modifiableBoxSelEquals),
		sourceSpecificity:    linkedhashmap.New[value.SimpleSelector, int](value.SimpleSelectorEquals),
		originals:            make(map[*value.ComplexSelector]struct{}),
		mode:                 mode,
	}
}

// newExtensionStoreInternal rebuilds a store from existing maps for Clone.
// The clone always runs in normal mode: function modes are transient and
// never survive a stylesheet copy.
func newExtensionStoreInternal(
	selectors *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashSet[*box.ModifiableBox[*value.SelectorList]]],
	extensions *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]],
	extensionsByExtender *linkedhashmap.LinkedHashMap[value.SimpleSelector, []Extension],
	mediaContexts *linkedhashmap.LinkedHashMap[*box.ModifiableBox[*value.SelectorList], []*value.CssMediaQuery],
	sourceSpecificity *linkedhashmap.LinkedHashMap[value.SimpleSelector, int],
	originals map[*value.ComplexSelector]struct{},
) *DefaultExtensionStore {
	return &DefaultExtensionStore{
		selectors:            selectors,
		extensions:           extensions,
		extensionsByExtender: extensionsByExtender,
		mediaContexts:        mediaContexts,
		sourceSpecificity:    sourceSpecificity,
		originals:            originals,
		mode:                 ExtendModeNormal,
	}
}

// modifiableBoxSelEquals compares selector boxes by box identity, so two
// boxes holding equal selector lists still count as distinct entries.
func modifiableBoxSelEquals(a, b *box.ModifiableBox[*value.SelectorList]) bool {
	return a.ID() == b.ID()
}

// IsEmpty reports whether the store holds no extensions. Selector
// registrations alone do not count.
func (store *DefaultExtensionStore) IsEmpty() bool {
	return store.extensions.Len() == 0
}

// SimpleSelectors returns every simple selector handled by the store,
// including ones added by downstream extensions.
func (store *DefaultExtensionStore) SimpleSelectors() []value.SimpleSelector {
	result := make([]value.SimpleSelector, 0, store.selectors.Len())
	for s := range store.selectors.Keys() {
		result = append(result, s)
	}
	return result
}

// ExtensionsWhereTarget returns the mandatory extensions whose targets
// satisfy callback. Merged extensions are unmerged first so only base
// (non-optional-leaf) rules come back.
func (store *DefaultExtensionStore) ExtensionsWhereTarget(callback func(value.SimpleSelector) bool) []Extension {
	var result []Extension
	for simple, sources := range store.extensions.Entries() {
		if !callback(simple) {
			continue
		}
		for _, ext := range sources.Entries() {
			if ext.IsMerged() {
				for _, u := range UnmergeExtensions(ext) {
					if !u.IsOptional() {
						result = append(result, u)
					}
				}
			} else if !ext.IsOptional() {
				result = append(result, ext)
			}
		}
	}
	return result
}

// AddSelector registers sel, extends it with the registered extensions, and
// returns a sealed box for the result. The box stays live: later extensions
// that match rewrite its value in place. Invisible selectors skip original
// tracking; mediaContext records where the rule was defined (nil at the top
// level). Extension failures are rethrown with the originating selector's
// location prefixed, matching Dart's "From <span>" wrapper.
func (store *DefaultExtensionStore) AddSelector(
	sel *value.SelectorList,
	mediaContext []*value.CssMediaQuery,
) (*box.Box[*value.SelectorList], error) {
	originalSelector := sel
	if !originalSelector.IsInvisible() {
		for _, c := range originalSelector.Components {
			store.originals[c] = struct{}{}
		}
	}

	if store.extensions.Len() > 0 {
		var err error
		sel, err = store.extendList(originalSelector, store.extensions, mediaContext)
		if err != nil {
			if se, ok := errors.AsType[*sasscommon.SassException](err); ok {
				spanMsg, err := spanMessage(se.Span)
				if err != nil {
					return nil, err
				}
				return nil, sasscommon.ThrowWithTrace(
					&sasscommon.SassException{
						Message: fmt.Sprintf("From %s\n%s", spanMsg, se.Message),
						Span:    se.Span,
					},
					se,
				)
			}
			return nil, err
		}
	}

	modifiableSelector := box.NewModifiableBoxWithID(sel, store.nextBoxID)
	store.nextBoxID++
	if mediaContext != nil {
		store.mediaContexts.Put(modifiableSelector, mediaContext)
	}
	store.registerSelector(sel, modifiableSelector)

	return modifiableSelector.Seal(), nil
}

// registerSelector indexes every simple selector in list (including ones
// nested inside selector pseudos) to point at sel, so future extensions
// targeting those simples can find this selector.
func (store *DefaultExtensionStore) registerSelector(
	list *value.SelectorList,
	sel *box.ModifiableBox[*value.SelectorList],
) {
	for _, complex := range list.Components {
		for _, component := range complex.Components {
			for _, simple := range component.Selector.Components {
				m, ok := store.selectors.Get(simple)
				if !ok {
					m = linkedhashmap.NewLinkedHashSet[*box.ModifiableBox[*value.SelectorList]](modifiableBoxSelEquals)
					store.selectors.Put(simple, m)
				}
				m.Add(sel)

				if ps, ok := simple.(*value.PseudoSelector); ok && ps.Selector != nil {
					if innerList, ok := ps.Selector.(*value.SelectorList); ok {
						store.registerSelector(innerList, sel)
					}
				}
			}
		}
	}
}

// AddExtension registers extender {@extend target} for the rule extend,
// restricted to mediaContext (nil means any context). Each extender complex
// selector becomes one Extension, skipping useless ones; a repeat extender
// for the same target merges with the existing entry (which may promote it
// to mandatory) instead of re-running extension. New extensions are applied
// to already-registered selectors and to existing extenders whose bodies
// mention the target, so chained extends like `.c {@extend .a}` followed by
// `.x.y.a {@extend .b}` propagate through the earlier extender.
func (store *DefaultExtensionStore) AddExtension(
	extender *value.SelectorList,
	target value.SimpleSelector,
	extend *value.ExtendRule,
	mediaContext []*value.CssMediaQuery,
) error {
	selectors, selectorsOk := store.selectors.Get(target)
	_, existingExtOk := store.extensionsByExtender.Get(target)

	type newExtEntry struct {
		complex *value.ComplexSelector
		ext     Extension
	}
	var newExtensions []newExtEntry
	sources, sourcesOk := store.extensions.Get(target)
	if !sourcesOk {
		sources = linkedhashmap.New[*value.ComplexSelector, Extension](value.ComplexSelectorEquals)
		store.extensions.Put(target, sources)
	}

	for _, complex := range extender.Components {
		if complex.IsUseless() {
			continue
		}

		extendSpan, err := extend.Span()
		if err != nil {
			return err
		}
		extension := NewExtension(complex, target, extendSpan, mediaContext, extend.IsOptional)

		if existingExtension, ok := sources.Get(complex); ok {
			merged, err := MergeExtensions(existingExtension, extension)
			if err != nil {
				return err
			}
			sources.Put(complex, merged)
			continue
		}
		sources.Put(complex, extension)

		for _, simple := range store.simpleSelectorsInComplex(complex) {
			exts, _ := store.extensionsByExtender.Get(simple)
			store.extensionsByExtender.Put(simple, append(exts, extension))
			if _, ok := store.sourceSpecificity.Get(simple); !ok {
				store.sourceSpecificity.Put(simple, complex.Specificity())
			}
		}

		if selectorsOk || existingExtOk {
			newExtensions = append(newExtensions, newExtEntry{complex, extension})
		}
	}

	if newExtensions == nil {
		return nil
	}

	newExtensionsByTarget := linkedhashmap.New[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]](value.SimpleSelectorEquals)
	newExtensionsMap := linkedhashmap.New[*value.ComplexSelector, Extension](value.ComplexSelectorEquals)
	for _, entry := range newExtensions {
		newExtensionsMap.Put(entry.complex, entry.ext)
	}
	newExtensionsByTarget.Put(target, newExtensionsMap)

	if existingExtOk {
		existingExtensions, _ := store.extensionsByExtender.Get(target)
		additionalExtensions, err := store.extendExistingExtensions(existingExtensions, newExtensionsByTarget)
		if err != nil {
			return err
		}
		if additionalExtensions.Len() > 0 {
			for t, m := range additionalExtensions.Entries() {
				if targetMap, ok := newExtensionsByTarget.Get(t); ok {
					for k, v := range m.Entries() {
						targetMap.Put(k, v)
					}
				} else {
					inner := linkedhashmap.New[*value.ComplexSelector, Extension](value.ComplexSelectorEquals)
					for k, v := range m.Entries() {
						inner.Put(k, v)
					}
					newExtensionsByTarget.Put(t, inner)
				}
			}
		}
	}

	if selectorsOk {
		if err := store.extendExistingSelectors(selectors, newExtensionsByTarget); err != nil {
			return err
		}
	}
	return nil
}

// simpleSelectorsInComplex yields every simple selector in complex,
// descending into selector pseudos so extensions registered on nested
// simples are also indexed by extender.
func (store *DefaultExtensionStore) simpleSelectorsInComplex(complex *value.ComplexSelector) []value.SimpleSelector {
	var result []value.SimpleSelector
	for _, component := range complex.Components {
		for _, simple := range component.Selector.Components {
			result = append(result, simple)

			if ps, ok := simple.(*value.PseudoSelector); ok && ps.Selector != nil {
				if innerList, ok := ps.Selector.(*value.SelectorList); ok {
					for _, innerComplex := range innerList.Components {
						result = append(result, store.simpleSelectorsInComplex(innerComplex)...)
					}
				}
			}
		}
	}
	return result
}

// Extend extends sel as though `source {@extend target}` were written for
// each compound target in targets, preserving existing selectors. Compound
// targets must extend as a unit; a complex target is a script error.
func (store *DefaultExtensionStore) Extend(
	sel *value.SelectorList,
	source *value.SelectorList,
	targets *value.SelectorList,
	span sasscommon.FileSpan,
) (*value.SelectorList, error) {
	return store.extendOrReplace(sel, source, targets, ExtendModeAllTargets, span)
}

// Replace returns a copy of sel with each compound target in targets
// replaced by source, dropping the original selectors. A complex target is
// a script error.
func (store *DefaultExtensionStore) Replace(
	sel *value.SelectorList,
	source *value.SelectorList,
	targets *value.SelectorList,
	span sasscommon.FileSpan,
) (*value.SelectorList, error) {
	return store.extendOrReplace(sel, source, targets, ExtendModeReplace, span)
}

// extendOrReplace backs Extend and Replace. It builds a throwaway store in
// the requested mode, seeds originals from sel (unless invisible), turns
// each target compound's simples into optional extensions from every source
// complex, and extends sel target by target through extendList.
func (store *DefaultExtensionStore) extendOrReplace(
	sel *value.SelectorList,
	source *value.SelectorList,
	targets *value.SelectorList,
	mode ExtendMode,
	span sasscommon.FileSpan,
) (*value.SelectorList, error) {
	extender := NewDefaultExtensionStoreWithMode(mode)
	if !sel.IsInvisible() {
		for _, c := range sel.Components {
			extender.originals[c] = struct{}{}
		}
	}

	for _, complex := range targets.Components {
		compound := complex.SingleCompound()
		if compound == nil {
			str, err := complex.String()
			if err != nil {
				return nil, err
			}
			return nil, sasscommon.NewSassScriptException(fmt.Sprintf("Can't extend complex selector %s.", str), nil)
		}

		extensions := linkedhashmap.New[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]](value.SimpleSelectorEquals)
		for _, simple := range compound.Components {
			extMap := linkedhashmap.New[*value.ComplexSelector, Extension](value.ComplexSelectorEquals)
			for _, srcComplex := range source.Components {
				extMap.Put(srcComplex, NewExtension(srcComplex, simple, span, nil, true))
			}
			extensions.Put(simple, extMap)
		}

		var err error
		sel, err = extender.extendList(sel, extensions, nil)
		if err != nil {
			return nil, err
		}
	}

	return sel, nil
}

// extendExistingExtensions extends each existing extender body with the new
// extensions, without reference to a full selector list so results are not
// trimmed too early. This duplicates some of extendExistingSelectors'
// work deliberately. Newly produced extender variants merge into (or join)
// the target's source map and are indexed by extender; variants created for
// a target that itself just gained extensions are returned as additional
// extensions so extension loops such as `.c {@extend .a}` / `.x.y.a
// {@extend .b}` / `.z.b {@extend .c}` resolve in the same pass. Failures
// carry the extender's span as a "target selector" secondary span.
func (store *DefaultExtensionStore) extendExistingExtensions(
	extensions []Extension,
	newExtensions *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]],
) (*linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]], error) {
	var additionalExtensions *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]]

	for _, extension := range extensions {
		sources, _ := store.extensions.Get(extension.Target())

		selectors, err := store.extendComplex(extension.Extender().Selector, newExtensions, extension.MediaContext())
		if err != nil {
			if se, ok := errors.AsType[*sasscommon.SassException](err); ok {
				selectorSpan, err := extension.Extender().Selector.Span()
				if err != nil {
					return additionalExtensions, err
				}
				return additionalExtensions, sasscommon.ThrowWithTrace(
					se.WithAdditionalSpan(selectorSpan, "target selector"),
					se,
				)
			}
			return additionalExtensions, err
		}
		// Without the target in the output there is nothing to rebuild, so the
		// extension keeps its current form.
		if selectors == nil {
			continue
		}

		// The extender itself always appears first in its own expansion, so
		// drop it and keep only the genuinely new variants.
		containsExtension := len(selectors) > 0 && selectors[0].Equals(extension.Extender().Selector)
		if containsExtension {
			selectors = selectors[1:]
		}

		for _, complex := range selectors {
			withExtender := extension.WithExtender(complex)
			if existingExtension, ok := sources.Get(complex); ok {
				merged, err := MergeExtensions(existingExtension, withExtender)
				if err != nil {
					return additionalExtensions, err
				}
				sources.Put(complex, merged)
			} else {
				sources.Put(complex, withExtender)

				for _, component := range complex.Components {
					for _, simple := range component.Selector.Components {
						exts, _ := store.extensionsByExtender.Get(simple)
						store.extensionsByExtender.Put(simple, append(exts, withExtender))
					}
				}

				if _, ok := newExtensions.Get(extension.Target()); ok {
					if additionalExtensions.Len() == 0 {
						additionalExtensions = linkedhashmap.New[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]](value.SimpleSelectorEquals)
					}
					inner, ok := additionalExtensions.Get(extension.Target())
					if !ok {
						inner = linkedhashmap.New[*value.ComplexSelector, Extension](value.ComplexSelectorEquals)
						additionalExtensions.Put(extension.Target(), inner)
					}
					inner.Put(complex, withExtender)
				}
			}
		}
	}

	return additionalExtensions, nil
}

// extendExistingSelectors rewrites each registered selector box with the
// new extensions, using the box's media context. A selector whose box value
// is unchanged (unification failed, for example) is not re-registered;
// failures are rethrown with the old value's location prefixed.
func (store *DefaultExtensionStore) extendExistingSelectors(
	selectors *linkedhashmap.LinkedHashSet[*box.ModifiableBox[*value.SelectorList]],
	newExtensions *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]],
) error {
	for selector := range selectors.Keys() {
		oldValue := selector.Value
		var err error
		mc, _ := store.mediaContexts.Get(selector)
		selector.Value, err = store.extendList(
			selector.Value,
			newExtensions,
			mc,
		)
		if err != nil {
			if se, ok := errors.AsType[*sasscommon.SassException](err); ok {
				oldValueSpan, err := oldValue.Span()
				if err != nil {
					return err
				}
				spanMsg, err := spanMessage(oldValueSpan)
				if err != nil {
					return err
				}
				return sasscommon.ThrowWithTrace(
					&sasscommon.SassException{
						Message: fmt.Sprintf("From %s\n%s", spanMsg, se.Message),
						Span:    se.Span,
					},
					se,
				)
			}
			return err
		}

		if oldValue == selector.Value {
			continue
		}
		store.registerSelector(selector.Value, selector)
	}
	return nil
}

// AddExtensions folds every extension from extensionStores into the
// receiver. Incoming extensions reach selectors already present and
// extenders already defined, but they never extend each other: that keeps
// cross-module merges from creating extension loops that cannot exist
// across module boundaries (so the extend-loop remainder from
// extendExistingExtensions is safely ignored here). Private placeholders
// never cross module boundaries, and source specificity merges across.
func (store *DefaultExtensionStore) AddExtensions(extensionStores []ExtensionStore) error {
	var extensionsToExtend []Extension
	var selectorsToExtend *linkedhashmap.LinkedHashSet[*box.ModifiableBox[*value.SelectorList]]
	var newExtensions *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]]

	for _, es := range extensionStores {
		if es.IsEmpty() {
			continue
		}
		// The empty sentinel carries no maps to merge; anything else is the
		// concrete store.
		extensionStore := es.(*DefaultExtensionStore)

		for k, v := range extensionStore.sourceSpecificity.Entries() {
			store.sourceSpecificity.Put(k, v)
		}

		for target, newSources := range extensionStore.extensions.Entries() {
			// Private placeholders are module-local and never extend across.
			if ps, ok := target.(*value.PlaceholderSelector); ok && ps.IsPrivate() {
				continue
			}

			extensionsForTarget, _ := store.extensionsByExtender.Get(target)
			if len(extensionsForTarget) > 0 {
				extensionsToExtend = append(extensionsToExtend, extensionsForTarget...)
			}

			selectorsForTarget, selectorsOk := store.selectors.Get(target)
			if selectorsOk {
				if selectorsToExtend == nil {
					selectorsToExtend = linkedhashmap.NewLinkedHashSet[*box.ModifiableBox[*value.SelectorList]](modifiableBoxSelEquals)
				}
				for s := range selectorsForTarget.Keys() {
					selectorsToExtend.Add(s)
				}
			}

			if existingSources, sourcesOk := store.extensions.Get(target); sourcesOk {
				for extKey, extension := range newSources.Entries() {
					if existing, ok := existingSources.Get(extKey); ok {
						merged, err := MergeExtensions(existing, extension)
						if err != nil {
							return err
						}
						extension = merged
						existingSources.Put(extKey, extension)
					} else {
						existingSources.Put(extKey, extension)
					}

					if len(extensionsForTarget) > 0 || selectorsOk {
						if newExtensions.Len() == 0 {
							newExtensions = linkedhashmap.New[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]](value.SimpleSelectorEquals)
						}
						targetMap, ok := newExtensions.Get(target)
						if !ok {
							targetMap = linkedhashmap.New[*value.ComplexSelector, Extension](value.ComplexSelectorEquals)
							newExtensions.Put(target, targetMap)
						}
						targetMap.Put(extKey, extension)
					}
				}
			} else {
				newMap := linkedhashmap.New[*value.ComplexSelector, Extension](value.ComplexSelectorEquals)
				for extKey, extension := range newSources.Entries() {
					newMap.Put(extKey, extension)
				}
				store.extensions.Put(target, newMap)
				if len(extensionsForTarget) > 0 || selectorsOk {
					if newExtensions.Len() == 0 {
						newExtensions = linkedhashmap.New[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]](value.SimpleSelectorEquals)
					}
					inner := linkedhashmap.New[*value.ComplexSelector, Extension](value.ComplexSelectorEquals)
					for extKey, extension := range newSources.Entries() {
						inner.Put(extKey, extension)
					}
					newExtensions.Put(target, inner)
				}
			}
		}
	}

	if newExtensions.Len() > 0 {
		if extensionsToExtend != nil {
			_, err := store.extendExistingExtensions(extensionsToExtend, newExtensions)
			if err != nil {
				return err
			}
		}
		if selectorsToExtend != nil {
			err := store.extendExistingSelectors(selectorsToExtend, newExtensions)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// Clone copies the store and maps each original selector list to its sealed
// copy. Selector boxes shared by several simples produce a single new box,
// media contexts follow their boxes, and extension maps plus originals are
// shallow-copied so the clone extends independently from here on.
func (store *DefaultExtensionStore) Clone() (ExtensionStore, map[*value.SelectorList]*box.Box[*value.SelectorList]) {
	newSelectors := linkedhashmap.New[value.SimpleSelector, *linkedhashmap.LinkedHashSet[*box.ModifiableBox[*value.SelectorList]]](value.SimpleSelectorEquals)
	newMediaContexts := linkedhashmap.New[*box.ModifiableBox[*value.SelectorList], []*value.CssMediaQuery](modifiableBoxSelEquals)
	oldToNewSelectors := make(map[*value.SelectorList]*box.Box[*value.SelectorList])
	newBoxes := make(map[uint64]*box.ModifiableBox[*value.SelectorList])
	var maxID uint64

	for simple, selectors := range store.selectors.Entries() {
		newSelectorSet := linkedhashmap.NewLinkedHashSet[*box.ModifiableBox[*value.SelectorList]](modifiableBoxSelEquals)
		newSelectors.Put(simple, newSelectorSet)

		for s := range selectors.Keys() {
			newSelector, ok := newBoxes[s.ID()]
			if !ok {
				id := store.nextBoxID + uint64(len(newBoxes)) + 1
				if id > maxID {
					maxID = id
				}
				newSelector = box.NewModifiableBoxWithID(s.Value, id)
				newBoxes[s.ID()] = newSelector
			}
			newSelectorSet.Add(newSelector)
			oldToNewSelectors[s.Value] = newSelector.Seal()

			if mediaContext, ok := store.mediaContexts.Get(s); ok {
				newMediaContexts.Put(newSelector, mediaContext)
			}
		}
	}

	newExtensions := copyMapOfMap(store.extensions)
	newExtensionsByExtender := copyMapOfList(store.extensionsByExtender)
	newSourceSpecificity := linkedhashmap.New[value.SimpleSelector, int](value.SimpleSelectorEquals)
	for k, v := range store.sourceSpecificity.Entries() {
		newSourceSpecificity.Put(k, v)
	}
	newOriginals := make(map[*value.ComplexSelector]struct{})
	for k := range store.originals {
		newOriginals[k] = struct{}{}
	}

	result := newExtensionStoreInternal(newSelectors, newExtensions, newExtensionsByExtender, newMediaContexts, newSourceSpecificity, newOriginals)
	result.nextBoxID = maxID + 1
	return result, oldToNewSelectors
}

// extendList extends every complex selector in list. It avoids allocation
// when nothing matches by accumulating into extended only once the first
// successful expansion appears (prefixing the untouched leading complexes),
// then trims subselectors that originals do not protect and rebuilds the
// list. A nil result from extendComplex means "no match", never an empty
// expansion.
func (store *DefaultExtensionStore) extendList(
	list *value.SelectorList,
	extensions *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]],
	mediaQueryContext []*value.CssMediaQuery,
) (*value.SelectorList, error) {
	var extended []*value.ComplexSelector
	for i := 0; i < len(list.Components); i++ {
		complex := list.Components[i]
		result, err := store.extendComplex(complex, extensions, mediaQueryContext)
		if err != nil {
			return nil, err
		}
		if result == nil {
			if extended != nil {
				extended = append(extended, complex)
			}
		} else {
			if extended == nil {
				if i == 0 {
					extended = make([]*value.ComplexSelector, 0)
				} else {
					extended = make([]*value.ComplexSelector, i)
					copy(extended, list.Components[:i])
				}
			}
			extended = append(extended, result...)
		}
	}

	if extended == nil {
		return list, nil
	}

	trimmed, err := store.trim(extended, func(c *value.ComplexSelector) bool {
		_, ok := store.originals[c]
		return ok
	})
	if err != nil {
		return nil, err
	}
	listSpan, err := list.Span()
	if err != nil {
		return nil, err
	}
	result, err := value.NewSelectorList(trimmed, listSpan)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// extendComplex extends one complex selector and returns the replacement
// selector list contents, or nil when no component matched.
//
// Each compound component expands to a list of complex choices (see
// extendCompound). The worked example in Dart is `.a .b` with
// `.x .y {@extend .b}`: the per-component choices are `[[.a], [.b, .x .y]]`.
// Choices accumulate lazily in extendedNotExpanded to avoid allocation when
// nothing matches; leading combinators constrain the first component's
// expansion to combinator-compatible results. Every cross product path is
// then woven into output complexes, and copies of an originally-registered
// complex keep their original status (including :not() rewrites).
func (store *DefaultExtensionStore) extendComplex(
	complex *value.ComplexSelector,
	extensions *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]],
	mediaQueryContext []*value.CssMediaQuery,
) ([]*value.ComplexSelector, error) {
	if len(complex.LeadingCombinators) > 1 {
		return nil, nil
	}

	var extendedNotExpanded [][]*value.ComplexSelector
	isOriginal := false
	if _, ok := store.originals[complex]; ok {
		isOriginal = true
	}

	complexSpan, err := complex.Span()
	if err != nil {
		return nil, err
	}

	for i := 0; i < len(complex.Components); i++ {
		component := complex.Components[i]
		extended, err := store.extendCompound(component, extensions, mediaQueryContext, isOriginal)
		if err != nil {
			return nil, err
		}
		if extended == nil {
			if extendedNotExpanded != nil {
				cs, err := value.NewComplexSelector(
					nil,
					[]*value.ComplexSelectorComponent{component},
					complexSpan,
					complex.LineBreak,
				)
				if err != nil {
					return nil, err
				}
				extendedNotExpanded = append(extendedNotExpanded, []*value.ComplexSelector{cs})
			}
		} else if extendedNotExpanded != nil {
			extendedNotExpanded = append(extendedNotExpanded, extended)
		} else if i != 0 {
			firstComps := make([]*value.ComplexSelectorComponent, i)
			copy(firstComps, complex.Components[:i])
			cs, err := value.NewComplexSelector(
				complex.LeadingCombinators,
				firstComps,
				complexSpan,
				complex.LineBreak,
			)
			if err != nil {
				return nil, err
			}
			extendedNotExpanded = [][]*value.ComplexSelector{
				{cs},
				extended,
			}
		} else if len(complex.LeadingCombinators) == 0 {
			extendedNotExpanded = [][]*value.ComplexSelector{extended}
		} else {
			var combCompat []*value.ComplexSelector
			for _, newComplex := range extended {
				if len(newComplex.LeadingCombinators) == 0 || cssValuesEqual(complex.LeadingCombinators, newComplex.LeadingCombinators) {
					cs, err := value.NewComplexSelector(
						complex.LeadingCombinators,
						newComplex.Components,
						complexSpan,
						complex.LineBreak || newComplex.LineBreak,
					)
					if err != nil {
						return nil, err
					}
					combCompat = append(combCompat, cs)
				}
			}
			extendedNotExpanded = [][]*value.ComplexSelector{combCompat}
		}
	}

	if extendedNotExpanded == nil {
		return nil, nil
	}

	var result []*value.ComplexSelector
	first := true
	for _, path := range value.Paths(extendedNotExpanded) {
		weaveResult, err := value.Weave(path, complexSpan, &complex.LineBreak)
		if err != nil {
			return nil, err
		}
		for _, outputComplex := range weaveResult {
			if first {
				if _, ok := store.originals[complex]; ok {
					store.originals[outputComplex] = struct{}{}
				}
				first = false
			}
			result = append(result, outputComplex)
		}
	}

	return result, nil
}

// extendCompound extends one compound component and returns the replacement
// complexes, or nil when no simple in it matched.
//
// Each simple contributes a list of extender choices (see extendSimple);
// unmatched leading/trailing simples contribute their own original
// extenders so the cross product still anchors on the base selector. In
// replace/all-targets modes every target must be used or extension fails
// for this component. The single-simple fast path just reattaches the
// component combinators to each extender; otherwise the first path (always
// the original selector) is rebuilt without unification while remaining
// paths unify their extenders, gain combinators, and are trimmed with the
// original protected when inOriginal applies. For example `.a.b` with
// `.w .x {@extend .a}` and `.y .z {@extend .b}` offers
// `[[.a, .w .x], [.b, .y .z]]`, whose paths unify to
// `.a.b, .y .a.z, .w .x.b, .w .y .x.z, .y .w .x.z`.
func (store *DefaultExtensionStore) extendCompound(
	component *value.ComplexSelectorComponent,
	extensions *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]],
	mediaQueryContext []*value.CssMediaQuery,
	inOriginal bool,
) ([]*value.ComplexSelector, error) {
	var targetsUsed *linkedhashmap.LinkedHashSet[value.SimpleSelector]
	if store.mode != ExtendModeNormal && extensions.Len() >= 2 {
		targetsUsed = linkedhashmap.NewLinkedHashSet[value.SimpleSelector](value.SimpleSelectorEquals)
	}

	simples := component.Selector.Components

	var options [][]*Extender
	for i := range simples {
		simple := simples[i]
		extended, err := store.extendSimple(simple, extensions, mediaQueryContext, targetsUsed)
		if err != nil {
			return nil, err
		}
		if extended == nil {
			if options != nil {
				ext, err := store.extenderForSimple(simple)
				if err != nil {
					return nil, err
				}
				options = append(options, []*Extender{ext})
			}
		} else {
			if options == nil {
				options = make([][]*Extender, 0)
				if i != 0 {
					ext, err := store.extenderForCompound(simples[:i], component.Span)
					if err != nil {
						return nil, err
					}
					options = append(options, []*Extender{ext})
				}
			}
			options = append(options, extended...)
		}
	}

	if options == nil {
		return nil, nil
	}

	if targetsUsed != nil && targetsUsed.Len() != extensions.Len() {
		return nil, nil
	}

	// The single-simple fast path skips unification: each extender is
	// checked for media compatibility and rehung on the component
	// combinators, dropping results that turned useless.
	if len(options) == 1 {
		var result []*value.ComplexSelector
		for _, extender := range options[0] {
			if err := extender.AssertCompatibleMediaContext(mediaQueryContext); err != nil {
				return nil, err
			}
			complex := extender.Selector.WithAdditionalCombinators(component.Combinators, false)
			if complex.IsUseless() {
				continue
			}
			if result == nil {
				result = make([]*value.ComplexSelector, 0)
			}
			result = append(result, complex)
		}
		return result, nil
	}

	extenderPaths := value.Paths(options)
	var result []*value.ComplexSelector

	if store.mode != ExtendModeReplace {
		// The first path is always the original selector, rebuilt from the
		// extenders' trailing compounds (selector pseudos may have been
		// rewritten) without paying for unification.
		firstComps := make([]value.SimpleSelector, 0)
		for _, extender := range extenderPaths[0] {
			if len(extender.Selector.Components) > 0 {
				firstComps = append(firstComps, extender.Selector.Components[len(extender.Selector.Components)-1].Selector.Components...)
			}
		}
		componentSelectorSpan, err := component.Selector.Span()
		if err != nil {
			return nil, err
		}
		firstCompound, err := value.NewCompoundSelector(firstComps, componentSelectorSpan)
		if err != nil {
			return nil, err
		}
		cs, err := value.NewComplexSelector(
			nil,
			[]*value.ComplexSelectorComponent{
				value.NewComplexSelectorComponent(firstCompound, component.Combinators, component.Span),
			},
			component.Span,
			false,
		)
		if err != nil {
			return nil, err
		}
		result = append(result, cs)
	}

	startIdx := 0
	if store.mode != ExtendModeReplace {
		startIdx = 1
	}

	for _, path := range extenderPaths[startIdx:] {
		extended, err := store.unifyExtenders(path, mediaQueryContext, component.Span)
		if err != nil {
			return nil, err
		}
		if extended == nil {
			continue
		}
		for _, complex := range extended {
			withCombinators := complex.WithAdditionalCombinators(component.Combinators, false)
			if !withCombinators.IsUseless() {
				result = append(result, withCombinators)
			}
		}
	}

	isOriginalFn := func(*value.ComplexSelector) bool { return false }
	if inOriginal && store.mode != ExtendModeReplace {
		original := result[0]
		isOriginalFn = func(c *value.ComplexSelector) bool { return c == original }
	}

	trimmed, err := store.trim(result, isOriginalFn)
	if err != nil {
		return nil, err
	}
	return trimmed, nil
}

// extenderForCompound builds an original extender holding just simples,
// with specificity drawn from the source-specificity table.
func (store *DefaultExtensionStore) extenderForCompound(simples []value.SimpleSelector, span sasscommon.FileSpan) (*Extender, error) {
	compound, err := value.NewCompoundSelector(simples, span)
	if err != nil {
		return nil, err
	}
	cs, err := value.NewComplexSelector(nil,
		[]*value.ComplexSelectorComponent{
			value.NewComplexSelectorComponent(compound, nil, span),
		},
		span,
		false,
	)
	if err != nil {
		return nil, err
	}
	return NewExtender(
		cs,
		new(store.sourceSpecificityFor(compound)),
		true,
	), nil
}

// extenderForSimple builds an original extender holding just simple,
// defaulting specificity to the stored source specificity (zero when unseen).
func (store *DefaultExtensionStore) extenderForSimple(simple value.SimpleSelector) (*Extender, error) {
	spec, _ := store.sourceSpecificity.Get(simple)
	simpleSpan, err := simple.Span()
	if err != nil {
		return nil, err
	}
	compound, err := value.NewCompoundSelector([]value.SimpleSelector{simple}, simpleSpan)
	if err != nil {
		return nil, err
	}
	cs, err := value.NewComplexSelector(
		nil,
		[]*value.ComplexSelectorComponent{
			value.NewComplexSelectorComponent(
				compound,
				nil,
				simpleSpan,
			),
		},
		simpleSpan,
		false,
	)
	if err != nil {
		return nil, err
	}
	return NewExtender(
		cs,
		&spec,
		true,
	), nil
}

// extendSimple returns the extender choices that should replace simple, or
// nil when simple is not an extension target.
//
// Each returned element is one choice list to be combined with the other
// simples' choices via cross product. Selectors inside pseudos are extended
// first (see extendPseudo); each resulting pseudo then resolves through the
// plain path, falling back to its own original extender when unmatched. In
// replace mode the original simple contributes no choice; otherwise it
// contributes its original extender ahead of the registered extenders.
func (store *DefaultExtensionStore) extendSimple(
	simple value.SimpleSelector,
	extensions *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]],
	mediaQueryContext []*value.CssMediaQuery,
	targetsUsed *linkedhashmap.LinkedHashSet[value.SimpleSelector],
) ([][]*Extender, error) {
	// withoutPseudo resolves simple without descending into selector pseudos.
	withoutPseudo := func(s value.SimpleSelector) ([]*Extender, error) {
		extensionsForSimple, ok := extensions.Get(s)
		if !ok {
			return nil, nil
		}
		if targetsUsed != nil {
			targetsUsed.Add(s)
		}

		var result []*Extender
		if store.mode != ExtendModeReplace {
			ext, err := store.extenderForSimple(s)
			if err != nil {
				return nil, err
			}
			result = append(result, ext)
		}
		for _, ext := range extensionsForSimple.Entries() {
			result = append(result, ext.Extender())
		}
		return result, nil
	}

	if ps, ok := simple.(*value.PseudoSelector); ok && ps.Selector != nil {
		extended, err := store.extendPseudo(ps, extensions, mediaQueryContext)
		if err != nil {
			return nil, err
		}
		if extended != nil {
			var result [][]*Extender
			for _, pseudo := range extended {
				wps, err := withoutPseudo(pseudo)
				if err != nil {
					return nil, err
				}
				if wps != nil {
					result = append(result, wps)
				} else {
					ext, err := store.extenderForSimple(pseudo)
					if err != nil {
						return nil, err
					}
					result = append(result, []*Extender{ext})
				}
			}
			return result, nil
		}
	}

	wps, err := withoutPseudo(simple)
	if err != nil {
		return nil, err
	}
	if wps != nil {
		return [][]*Extender{wps}, nil
	}
	return nil, nil
}

// extendPseudo extends the selector argument of pseudo and returns the
// resulting pseudo selectors. A pseudo without a selector argument is a
// caller error; a non-list argument cannot be extended. :not() results are
// filtered to simple complexes when the original was simple-only and the
// expansion produced any, since complex :not() contents break older
// parsers. Nested pseudos then fold per outer name: :not() unwraps only
// :is/:matches/:where contents (a :not() inside :not() would need
// unification the port deliberately skips), the :is() family unwraps only
// same-name/same-argument contents, :has()/:host()/:host-context()/:slotted()
// keep the nested layer because each layer adds semantics, and anything
// else drops. A single-complex :not() splits back into one pseudo per
// complex for legacy browser support; other pseudos rebuild as one pseudo
// over the unified list.
func (store *DefaultExtensionStore) extendPseudo(
	pseudo *value.PseudoSelector,
	extensions *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]],
	mediaQueryContext []*value.CssMediaQuery,
) ([]value.SimpleSelector, error) {
	if pseudo.Selector == nil {
		return nil, &sasscommon.ArgumentError{Message: fmt.Sprintf("Selector %s must have a selector argument.", pseudo.Name)}
	}

	sel, ok := pseudo.Selector.(*value.SelectorList)
	if !ok {
		return nil, nil
	}

	selSpan, err := sel.Span()
	if err != nil {
		return nil, err
	}

	extended, err := store.extendList(sel, extensions, mediaQueryContext)
	if err != nil {
		return nil, err
	}
	if extended == sel {
		return nil, nil
	}

	complexes := extended.Components

	if pseudo.NormalizedName == "not" {
		origHasComplex := false
		for _, c := range sel.Components {
			if len(c.Components) > 1 {
				origHasComplex = true
				break
			}
		}
		extHasSimple := false
		for _, c := range extended.Components {
			if len(c.Components) <= 1 {
				extHasSimple = true
				break
			}
		}
		if !origHasComplex && extHasSimple {
			var filtered []*value.ComplexSelector
			for _, c := range extended.Components {
				if len(c.Components) <= 1 {
					filtered = append(filtered, c)
				}
			}
			complexes = filtered
		}
	}

	var resultComps []*value.ComplexSelector
	for _, complex := range complexes {
		innerPseudo := findSingleSimplePseudo(complex)
		if innerPseudo == nil {
			resultComps = append(resultComps, complex)
			continue
		}
		innerSelector, ok := innerPseudo.Selector.(*value.SelectorList)
		if !ok || innerSelector == nil {
			resultComps = append(resultComps, complex)
			continue
		}

		switch pseudo.NormalizedName {
		case "not":
			if innerPseudo.NormalizedName == "is" || innerPseudo.NormalizedName == "matches" || innerPseudo.NormalizedName == "where" {
				resultComps = append(resultComps, innerSelector.Components...)
			}
			// Other inner pseudos nested in :not() cannot be represented here and
		// are dropped.

		case "is", "matches", "where", "any", "current", "nth-child", "nth-last-child":
			if innerPseudo.Name == pseudo.Name && ptrEqString(innerPseudo.Argument, pseudo.Argument) {
				resultComps = append(resultComps, innerSelector.Components...)
			}

		case "has", "host", "host-context", "slotted":
			// Nested layers cannot be expanded here: each adds semantics, so
			// `:has(:has(img))` must not collapse to `:has(img)`.
			resultComps = append(resultComps, complex)

		default:
			// Unrecognized inner pseudos have no defined expansion and are dropped.
		}
	}

	if pseudo.NormalizedName == "not" && len(sel.Components) == 1 {
		var result []value.SimpleSelector
		for _, c := range resultComps {
			list, err := value.NewSelectorList([]*value.ComplexSelector{c}, selSpan)
			if err != nil {
				return nil, err
			}
			psel, err := pseudo.WithSelector(list)
			if err != nil {
				return nil, err
			}
			result = append(result, psel)
		}
		if len(result) == 0 {
			return nil, nil
		}
		return result, nil
	}

	list, err := value.NewSelectorList(resultComps, selSpan)
	if err != nil {
		return nil, err
	}
	psel, err := pseudo.WithSelector(list)
	if err != nil {
		return nil, err
	}
	result := []value.SimpleSelector{
		psel,
	}
	return result, nil
}

// findSingleSimplePseudo returns the pseudo when complex is exactly one
// compound of one simple that is a pseudo, or nil otherwise. It identifies
// the nested-pseudo shapes extendPseudo knows how to fold.
func findSingleSimplePseudo(complex *value.ComplexSelector) *value.PseudoSelector {
	if len(complex.LeadingCombinators) != 0 {
		return nil
	}
	if len(complex.Components) != 1 {
		return nil
	}
	comp := complex.Components[0]
	if len(comp.Combinators) != 0 {
		return nil
	}
	if len(comp.Selector.Components) != 1 {
		return nil
	}
	ps, ok := comp.Selector.Components[0].(*value.PseudoSelector)
	if !ok {
		return nil
	}
	return ps
}

// unifyExtenders returns complex selectors matching the intersection of
// everything the extenders match. Original extenders contribute their
// trailing simples to one shared compound (useless non-original extenders
// fail the whole unification); the originals compound leads so its
// line-break survives. The collected complexes unify, and every extender
// must then accept the application media context.
func (store *DefaultExtensionStore) unifyExtenders(
	extenders []*Extender,
	mediaQueryContext []*value.CssMediaQuery,
	span sasscommon.FileSpan,
) ([]*value.ComplexSelector, error) {
	var toUnify []*value.ComplexSelector
	var originals []value.SimpleSelector
	originalsLineBreak := false

	for _, extender := range extenders {
		if extender.IsOriginal {
			if len(extender.Selector.Components) > 0 {
				finalComp := extender.Selector.Components[len(extender.Selector.Components)-1]
				originals = append(originals, finalComp.Selector.Components...)
				originalsLineBreak = originalsLineBreak || extender.Selector.LineBreak
			}
		} else if extender.Selector.IsUseless() {
			return nil, nil
		} else {
			toUnify = append(toUnify, extender.Selector)
		}
	}

	if originals != nil {
		compound, err := value.NewCompoundSelector(originals, span)
		if err != nil {
			return nil, err
		}
		cs, err := value.NewComplexSelector(
			nil,
			[]*value.ComplexSelectorComponent{
				value.NewComplexSelectorComponent(
					compound,
					nil,
					span,
				),
			},
			span,
			originalsLineBreak,
		)
		if err != nil {
			return nil, err
		}
		toUnify = append([]*value.ComplexSelector{cs}, toUnify...)
	}

	complexes, err := value.UnifyComplex(toUnify, span)
	if err != nil {
		return nil, err
	}
	if complexes == nil {
		return nil, nil
	}

	for _, extender := range extenders {
		if err := extender.AssertCompatibleMediaContext(mediaQueryContext); err != nil {
			return nil, err
		}
	}

	return complexes, nil
}

// trim drops selectors that are subselectors of another surviving selector,
// where isOriginal marks document originals that must never be trimmed.
// Beyond a hundred candidates trimming is skipped to avoid quadratic blowup.
// The scan runs back to front and prepends survivors so that, for identical
// selectors, the first occurrence wins; duplicate originals rotate to the
// front instead of duplicating. A candidate is trimmed only when a surviving
// (or earlier) superselector also meets the maximum source specificity of
// the candidate's components, preserving selectors needed by the second law
// of extend.
func (store *DefaultExtensionStore) trim(
	selectors []*value.ComplexSelector,
	isOriginal func(*value.ComplexSelector) bool,
) ([]*value.ComplexSelector, error) {
	if len(selectors) > 100 {
		return selectors, nil
	}

	var result []*value.ComplexSelector
	numOriginals := 0

outer:
	for i := len(selectors) - 1; i >= 0; i-- {
		complex1 := selectors[i]
		if isOriginal(complex1) {
			for j := 0; j < numOriginals; j++ {
				if result[j].Equals(complex1) {
					rotateSlice(result, 0, j+1)
					continue outer
				}
			}
			numOriginals++
			result = append([]*value.ComplexSelector{complex1}, result...)
			continue
		}

		maxSpecificity := 0
		for _, component := range complex1.Components {
			maxSpecificity = max(maxSpecificity, store.sourceSpecificityFor(component.Selector))
		}

		found := false
		for _, complex2 := range result {
			sup, err := complex2.IsSuperselector(complex1)
			if err != nil {
				return nil, err
			}
			if complex2.Specificity() >= maxSpecificity && sup {
				found = true
				break
			}
		}
		if found {
			continue
		}

		for j := 0; j < i; j++ {
			complex2 := selectors[j]
			sup, err := complex2.IsSuperselector(complex1)
			if err != nil {
				return nil, err
			}
			if complex2.Specificity() >= maxSpecificity && sup {
				found = true
				break
			}
		}
		if found {
			continue
		}

		result = append([]*value.ComplexSelector{complex1}, result...)
	}

	return result, nil
}

// sourceSpecificityFor returns the maximum source specificity over the
// simples that produced compound, or zero when none were recorded.
func (store *DefaultExtensionStore) sourceSpecificityFor(compound *value.CompoundSelector) int {
	specificity := 0
	for _, simple := range compound.Components {
		if s, ok := store.sourceSpecificity.Get(simple); ok && s > specificity {
			specificity = s
		}
	}
	return specificity
}

// --- Static helper methods ---

// ExtendStatic extends sel with source over compound targets without a
// persistent store, backing the selector-extend() function.
func ExtendStatic(sel, source, targets *value.SelectorList, span sasscommon.FileSpan) (*value.SelectorList, error) {
	store := NewDefaultExtensionStoreWithMode(ExtendModeAllTargets)
	return store.extendOrReplace(sel, source, targets, ExtendModeAllTargets, span)
}

// ReplaceStatic returns a copy of sel with compound targets replaced by
// source, backing the selector-replace() function.
func ReplaceStatic(sel, source, targets *value.SelectorList, span sasscommon.FileSpan) (*value.SelectorList, error) {
	store := NewDefaultExtensionStoreWithMode(ExtendModeReplace)
	return store.extendOrReplace(sel, source, targets, ExtendModeReplace, span)
}

// --- Helpers ---

// ptrEqString reports whether two optional strings are equal, treating two
// nils as equal.
func ptrEqString(a, b *string) bool {
	if a == b {
		return true
	}
	if a == nil || b == nil {
		return false
	}
	return *a == *b
}

// cssValuesEqual reports whether two combinator slices are elementwise equal.
func cssValuesEqual(a, b []sasscommon.CssValue[value.Combinator]) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if !a[i].Equal(b[i]) {
			return false
		}
	}
	return true
}

// spanMessage renders span as `line L, column C of URL:` for the "From ..."
// prefixes on extension error reports.
func spanMessage(s sasscommon.FileSpan) (string, error) {
	u, err := s.SourceURL()
	if err != nil {
		return "", err
	}
	startLoc, err := s.StartLocation()
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("line %d, column %d of %s:", startLoc.Line+1, startLoc.Column+1, sasscommon.PrettyUri(u)), nil
}

// rotateSlice moves the element at start to end-1, shifting the middle
// left. It dedups repeated originals in trim by bringing the surviving
// copy to the front of the accumulator.
func rotateSlice[T any](slice []T, start, end int) {
	if start >= end || end > len(slice) {
		return
	}
	// Rotate so that the element at index start moves to index end-1
	n := end - start
	for i := 0; i < n-1; i++ {
		slice[start+i], slice[start+n-1] = slice[start+n-1], slice[start+i]
	}
}

// copyMapOfMap duplicates the target-to-sources extension map for Clone so
// the clone and original diverge from here on.
func copyMapOfMap(
	m *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]],
) *linkedhashmap.LinkedHashMap[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]] {
	result := linkedhashmap.New[value.SimpleSelector, *linkedhashmap.LinkedHashMap[*value.ComplexSelector, Extension]](value.SimpleSelectorEquals)
	for target, sources := range m.Entries() {
		inner := linkedhashmap.New[*value.ComplexSelector, Extension](value.ComplexSelectorEquals)
		for extKey, ext := range sources.Entries() {
			inner.Put(extKey, ext)
		}
		result.Put(target, inner)
	}
	return result
}

// copyMapOfList duplicates the extender index for Clone.
func copyMapOfList(
	m *linkedhashmap.LinkedHashMap[value.SimpleSelector, []Extension],
) *linkedhashmap.LinkedHashMap[value.SimpleSelector, []Extension] {
	result := linkedhashmap.New[value.SimpleSelector, []Extension](value.SimpleSelectorEquals)
	for target, exts := range m.Entries() {
		inner := make([]Extension, len(exts))
		copy(inner, exts)
		result.Put(target, inner)
	}
	return result
}
